FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app


COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt


COPY . .


EXPOSE 8000


CMD ["uvicorn", "src.main:app","--host" ,"0.0.0.0","--port","8000"]